package calculadoracliente;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author mbacelofernandez
 */
public class Calculadora extends javax.swing.JFrame {

    /**
     * Creates new form Calculadora
     */
    String valor,enviar;
    
    public Calculadora() {
        initComponents();
        setLocationRelativeTo(null);
        m.conexion();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jVaciar = new javax.swing.JButton();
        jApagar = new javax.swing.JButton();
        jSiete = new javax.swing.JButton();
        jOcho = new javax.swing.JButton();
        jNueve = new javax.swing.JButton();
        jDivision = new javax.swing.JButton();
        jCinco = new javax.swing.JButton();
        jSeis = new javax.swing.JButton();
        jCuatro = new javax.swing.JButton();
        jDos = new javax.swing.JButton();
        jMultiplicacion = new javax.swing.JButton();
        jUno = new javax.swing.JButton();
        jTres = new javax.swing.JButton();
        jResta = new javax.swing.JButton();
        jDecimal = new javax.swing.JButton();
        jCero = new javax.swing.JButton();
        jResultado = new javax.swing.JButton();
        jSuma = new javax.swing.JButton();
        jRaiz = new javax.swing.JButton();
        jPantalla = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jVaciar.setBackground(new java.awt.Color(255, 51, 51));
        jVaciar.setText("AC");
        jVaciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jVaciarActionPerformed(evt);
            }
        });

        jApagar.setBackground(new java.awt.Color(51, 102, 255));
        jApagar.setText("OFF");
        jApagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jApagarActionPerformed(evt);
            }
        });

        jSiete.setText("7");
        jSiete.setPreferredSize(new java.awt.Dimension(44, 25));
        jSiete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSieteActionPerformed(evt);
            }
        });

        jOcho.setText("8");
        jOcho.setPreferredSize(new java.awt.Dimension(44, 25));
        jOcho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jOchoActionPerformed(evt);
            }
        });

        jNueve.setText("9");
        jNueve.setPreferredSize(new java.awt.Dimension(44, 25));
        jNueve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNueveActionPerformed(evt);
            }
        });

        jDivision.setText("/");
        jDivision.setPreferredSize(new java.awt.Dimension(44, 25));
        jDivision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDivisionActionPerformed(evt);
            }
        });

        jCinco.setText("5");
        jCinco.setPreferredSize(new java.awt.Dimension(44, 25));
        jCinco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCincoActionPerformed(evt);
            }
        });

        jSeis.setText("6");
        jSeis.setPreferredSize(new java.awt.Dimension(44, 25));
        jSeis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSeisActionPerformed(evt);
            }
        });

        jCuatro.setText("4");
        jCuatro.setPreferredSize(new java.awt.Dimension(44, 25));
        jCuatro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCuatroActionPerformed(evt);
            }
        });

        jDos.setText("2");
        jDos.setPreferredSize(new java.awt.Dimension(44, 25));
        jDos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDosActionPerformed(evt);
            }
        });

        jMultiplicacion.setText("*");
        jMultiplicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMultiplicacionActionPerformed(evt);
            }
        });

        jUno.setText("1");
        jUno.setPreferredSize(new java.awt.Dimension(44, 25));
        jUno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jUnoActionPerformed(evt);
            }
        });

        jTres.setText("3");
        jTres.setPreferredSize(new java.awt.Dimension(44, 25));
        jTres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTresActionPerformed(evt);
            }
        });

        jResta.setText("-");
        jResta.setPreferredSize(new java.awt.Dimension(44, 25));
        jResta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRestaActionPerformed(evt);
            }
        });

        jDecimal.setText(".");
        jDecimal.setPreferredSize(new java.awt.Dimension(44, 25));
        jDecimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDecimalActionPerformed(evt);
            }
        });

        jCero.setText("0");
        jCero.setPreferredSize(new java.awt.Dimension(44, 25));
        jCero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCeroActionPerformed(evt);
            }
        });

        jResultado.setText("=");
        jResultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jResultadoActionPerformed(evt);
            }
        });

        jSuma.setText("+");
        jSuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSumaActionPerformed(evt);
            }
        });

        jRaiz.setText("√");
        jRaiz.setMargin(null);
        jRaiz.setMaximumSize(new java.awt.Dimension(37, 25));
        jRaiz.setMinimumSize(new java.awt.Dimension(37, 25));
        jRaiz.setPreferredSize(new java.awt.Dimension(37, 25));
        jRaiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRaizActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jCero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jDecimal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jUno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jDos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jCuatro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jCinco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jSiete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jOcho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jSeis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jMultiplicacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jTres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jResta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSuma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(jNueve, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDivision, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jVaciar)
                        .addGap(18, 18, 18)
                        .addComponent(jApagar)
                        .addGap(14, 14, 14)
                        .addComponent(jRaiz, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jApagar)
                    .addComponent(jVaciar)
                    .addComponent(jRaiz, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSiete, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jOcho, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jNueve, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDivision, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCinco, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeis, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCuatro, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jMultiplicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jDos, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTres, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jResta, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jUno, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCero, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDecimal, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSuma, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 16, Short.MAX_VALUE))
        );

        jPantalla.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jPantalla.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPantalla.setFocusable(false);
        jPantalla.setMaximumSize(new java.awt.Dimension(10, 27));
        jPantalla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPantallaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPantalla, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPantalla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(31, 31, 31))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jDivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDivisionActionPerformed
        enviar = jPantalla.getText()+" "+"division";
        jPantalla.setText(null);
    }//GEN-LAST:event_jDivisionActionPerformed

    private void jCeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCeroActionPerformed
       jPantalla.setText(jPantalla.getText()+"0");
    }//GEN-LAST:event_jCeroActionPerformed

    private void jUnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jUnoActionPerformed
        jPantalla.setText(jPantalla.getText()+"1");
    }//GEN-LAST:event_jUnoActionPerformed

    private void jDosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDosActionPerformed
        jPantalla.setText(jPantalla.getText()+"2");
    }//GEN-LAST:event_jDosActionPerformed

    private void jTresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTresActionPerformed
        jPantalla.setText(jPantalla.getText()+"3");
    }//GEN-LAST:event_jTresActionPerformed

    private void jCuatroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCuatroActionPerformed
       jPantalla.setText(jPantalla.getText()+"4");
    }//GEN-LAST:event_jCuatroActionPerformed

    private void jCincoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCincoActionPerformed
       jPantalla.setText(jPantalla.getText()+"5");
    }//GEN-LAST:event_jCincoActionPerformed

    private void jSeisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSeisActionPerformed
        jPantalla.setText(jPantalla.getText()+"6");
    }//GEN-LAST:event_jSeisActionPerformed

    private void jSieteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSieteActionPerformed
        jPantalla.setText(jPantalla.getText()+"7");
    }//GEN-LAST:event_jSieteActionPerformed

    private void jOchoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jOchoActionPerformed
        jPantalla.setText(jPantalla.getText()+"8");
    }//GEN-LAST:event_jOchoActionPerformed

    private void jNueveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNueveActionPerformed
        jPantalla.setText(jPantalla.getText()+"9");
    }//GEN-LAST:event_jNueveActionPerformed
    /*
    Cerramos el cliente llamando al metodo pecharConexion de la clase Metodos
    */
    private void jApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jApagarActionPerformed
        try {
            m.pecharConexion();
        } catch (IOException ex) {
            Logger.getLogger(Calculadora.class.getName()).log(Level.SEVERE, null, ex);
        }
        System.exit(0);
    }//GEN-LAST:event_jApagarActionPerformed

    private void jVaciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jVaciarActionPerformed
        jPantalla.setText(null);
    }//GEN-LAST:event_jVaciarActionPerformed

    private void jMultiplicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMultiplicacionActionPerformed
        enviar = jPantalla.getText()+" "+"multiplicacion";
        jPantalla.setText(null);
    }//GEN-LAST:event_jMultiplicacionActionPerformed
    /*
    Dependiendo de si el signo - está antes o despies del operando, asignará el 
    valor negativo o significará que queremos realizar una resta 
    */
    private void jRestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRestaActionPerformed
        if(jPantalla.getText().equalsIgnoreCase("")){
           jPantalla.setText("-");
        }else{
             enviar = jPantalla.getText()+" "+"resta";
             jPantalla.setText(null);
        }
    }//GEN-LAST:event_jRestaActionPerformed

    private void jSumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSumaActionPerformed
        enviar = jPantalla.getText()+" "+"suma";
        jPantalla.setText(null);
    }//GEN-LAST:event_jSumaActionPerformed
    /*
    Recogemos los operandos en una variable y los enviamos al metodo operacion de la clase
    Metodos, y vaciamos las variables
    */
    private void jResultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jResultadoActionPerformed
 
       enviar = enviar+ " "+jPantalla.getText(); 
       jPantalla.setText("");
        try {
            String aux = m.operacion(enviar);
            jPantalla.setText(String.format("%.2f", Float.parseFloat(aux)));
            enviar = null;
        } catch (IOException ex) {
            Logger.getLogger(Calculadora.class.getName()).log(Level.SEVERE, null, ex);
        }
        


        
    }//GEN-LAST:event_jResultadoActionPerformed

    private void jDecimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDecimalActionPerformed
        jPantalla.setText(jPantalla.getText()+".");
    }//GEN-LAST:event_jDecimalActionPerformed

    private void jRaizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRaizActionPerformed
         enviar = "raiz";
    }//GEN-LAST:event_jRaizActionPerformed

    private void jPantallaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPantallaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPantallaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculadora().setVisible(true);
                             
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jApagar;
    private javax.swing.JButton jCero;
    private javax.swing.JButton jCinco;
    private javax.swing.JButton jCuatro;
    private javax.swing.JButton jDecimal;
    private javax.swing.JButton jDivision;
    private javax.swing.JButton jDos;
    private javax.swing.JButton jMultiplicacion;
    private javax.swing.JButton jNueve;
    private javax.swing.JButton jOcho;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jPantalla;
    private javax.swing.JButton jRaiz;
    private javax.swing.JButton jResta;
    private javax.swing.JButton jResultado;
    private javax.swing.JButton jSeis;
    private javax.swing.JButton jSiete;
    private javax.swing.JButton jSuma;
    private javax.swing.JButton jTres;
    private javax.swing.JButton jUno;
    private javax.swing.JButton jVaciar;
    // End of variables declaration//GEN-END:variables
Metodos m = new Metodos();
}
